# Generated by Django 5.1.7 on 2025-03-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("predicted_image", models.ImageField(null=True, upload_to="")),
                ("offside_perc", models.FloatField(null=True)),
            ],
        ),
    ]
